    ~~~~~ Developed By: Muhammad Umair Habib ~~~~~

Data is available in the form of csv file.

Requirements:

Q1: What are the different subjects/courses Udemy offers?

Q2: Find out the maximum number of courses each category has?

Q3: Show all the courses which are free of cost?

Q4: Show all the courses which are paid?

Q5: Which are the top selling courses?

Q6: Which are the least selling courses?

Q7: Show all the courses of graphic design, where the prices are below 100.

Q8: Find out all the courses which are related to Python.

Q9: Courses published in 2017.

Q10: What are the maximum number of subscribers for each level of course?

In [1]:
import pandas as pd

In [3]:
udemy_courses = pd.read_csv("Udemy+Courses.csv")

In [4]:
udemy_courses

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments
...,...,...,...,...,...,...,...,...,...,...,...
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26T20:04:21Z,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development
3680,1225194,Zoho Books Gestion Financière d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26T16:45:55Z,Business Finance
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

In [5]:
udemy_courses.shape

(3682, 11)

    Use (subject) column and unique function
Q1: What are the different subjects/courses Udemy offers?

In [7]:
udemy_courses.head(2)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments

In [8]:
udemy_courses.subject.unique()

array(['Musical Instruments', 'Business Finance', 'Graphic Design',
       'Web Development'], dtype=object)

    Use column subject and value_counts (Shows unique values/category of the column)
Q2: Find out the maximum number of courses each category has?

In [9]:
udemy_courses.head(2)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments

In [10]:
udemy_courses.subject.value_counts()

subject
Web Development        1200
Business Finance       1199
Musical Instruments     680
Graphic Design          603
Name: count, dtype: int64

    Use is_paid column
Q3: Show all the courses which are free of cost?

In [11]:
udemy_courses.head(2)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments

In [12]:
udemy_courses.is_paid == False # False mean free, True mean paid

0       False
1       False
2       False
3       False
4       False
        ...
3677    False
3678    False
3679    False
3680     True
3681    False
Name: is_paid, Length: 3682, dtype: bool

In [13]:
# If you want to see the data in data-frame
udemy_courses[udemy_courses.is_paid == False]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
41,286070,5 lecciones que todo guitarrista debe tomar,False,Free,4452,263,14,Beginner Level,1 hour,2014-08-23T05:08:14Z,Musical Instruments
49,696630,"7 Ways A Beginner Guitarist Can Sound Better, ...",False,Free,4529,193,7,Beginner Level,36 mins,2015-12-21T18:50:50Z,Musical Instruments
57,955914,A beginner`s guide to fingerpicking and strumm...,False,Free,3481,29,20,Beginner Level,2 hours,2016-09-13T21:51:59Z,Musical Instruments
67,270976,A how to guide in HTML,False,Free,7318,205,8,Beginner Level,35 mins,2014-08-10T20:19:10Z,Web Development
74,1214144,¡Triunfar en La Bolsa de Valores No Requiere d...,False,Free,338,7,6,Beginner Level,1 hour,2017-05-30T14:30:12Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3620,552598,WordPress in under an hour - Create/manage you...,False,Free,6474,86,15,All Levels,1 hour,2015-07-15T00:21:56Z,Web Development
3638,1068590,Wordpress Website Mastery 2017,False,Free,5181,64,22,Beginner Level,2.5 hours,2017-01-18T17:01:40Z,Web Development
3652,752706,Write quicker HTML5 and CSS 3; productivity ha...,False,Free,13016,286,15,All Levels,1.5 hours,2016-03-03T17:45:31Z,Web Development
3674,1257976,Your First 10 Guitar Lessons - Learn how to pl...,False,Free,924,4,18,Beginner Level,1 hour,2017-06-29T00:29:36Z,Musical Instruments
3680,1225194,Zoho Books Gestion Financière d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26T16:45:55Z,Business Finance

In [14]:
# Check the shape
udemy_courses[udemy_courses.is_paid == False].shape

(310, 11)

Q4: Show all the courses which are paid?

In [15]:
udemy_courses.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments

In [16]:
udemy_courses[udemy_courses.is_paid == True]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments
...,...,...,...,...,...,...,...,...,...,...,...
3676,498488,Your First Successful Forex Trades - With Case...,True,200,1079,34,16,All Levels,2.5 hours,2015-05-26T20:48:48Z,Business Finance
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26T20:04:21Z,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

In [17]:
udemy_courses[udemy_courses.is_paid == True].shape

(3372, 11)

    num_subscribers column, and sort_values function 
Q5: Which are the top selling courses?

In [19]:
udemy_courses.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments

In [21]:
# By default ascending = True
udemy_courses.sort_values('num_subscribers', ascending = False)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
...,...,...,...,...,...,...,...,...,...,...,...
1390,1136038,Free Ways to Create Passive Income Online,True,25,0,0,27,Beginner Level,1 hour,2017-04-17T22:33:13Z,Business Finance
1909,1157298,Introduction to Forex Trading Business For Beg...,True,20,0,0,27,Beginner Level,1.5 hours,2017-04-23T16:19:01Z,Business Finance
1910,1157298,Introduction to Forex Trading Business For Beg...,True,20,0,0,27,Beginner Level,1.5 hours,2017-04-23T16:19:01Z,Business Finance
1325,1187084,Forex how traders beat the markest with little...,True,100,0,0,16,All Levels,1 hour,2017-07-06T21:16:13Z,Business Finance
44,1231958,60 Minutes to Fundamental Accounting Skills,True,75,0,0,9,Beginner Level,2.5 hours,2017-06-28T21:55:29Z,Business Finance

    By default ascending = True
Q6: Which are the least selling courses?

In [22]:
udemy_courses.sort_values('num_subscribers')

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
98,1219820,Accounting - The 6 most important rules you mu...,True,20,0,0,9,All Levels,1 hour,2017-05-25T21:55:50Z,Business Finance
2350,371900,Learn to create Text fire effect in Adobe Phot...,True,20,0,0,8,All Levels,36 mins,2014-12-19T23:19:47Z,Graphic Design
3221,1057040,Teeter-Totter Accounting,True,90,0,0,12,Beginner Level,1 hour,2017-02-08T22:15:56Z,Business Finance
649,1233314,Building a Balanced Scorecard,True,50,0,0,11,Intermediate Level,2 hours,2017-07-03T21:38:22Z,Business Finance
954,1169196,"Credit concepts and checklist for bankers, cre...",True,20,0,0,10,Beginner Level,2.5 hours,2017-04-24T14:56:01Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development

    Subject and price columns (use filter and & operator)
Q7: Show all the courses of graphic design, where the prices are below 100.

In [23]:
udemy_courses.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments

In [24]:
udemy_courses.subject == 'Graphic Design'

0       False
1       False
2       False
3       False
4       False
        ...
3677    False
3678    False
3679    False
3680    False
3681     True
Name: subject, Length: 3682, dtype: bool

In [26]:
# Result in data-frame
udemy_courses[udemy_courses.subject == 'Graphic Design']

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
8,206592,:::Beginners Guide To Creating Amazing Images ...,True,25,72,5,17,Beginner Level,1 hour,2014-04-29T19:50:31Z,Graphic Design
20,1165268,15 Motion Graphic Elements in After Effect (S...,True,30,8,0,20,Intermediate Level,3 hours,2017-04-11T04:27:34Z,Graphic Design
35,1164876,3DS MAX - Learn 3Ds MAX tutorial for Beginners...,True,20,785,2,29,All Levels,4.5 hours,2017-04-18T16:45:59Z,Graphic Design
39,599652,48 Logo Designs and Techniques,True,20,113,9,48,All Levels,9 hours,2015-09-15T00:23:14Z,Graphic Design
47,1269190,7 Secrets To Designing In Black and White,True,100,1000,1,12,All Levels,1.5 hours,2017-06-27T19:55:18Z,Graphic Design
...,...,...,...,...,...,...,...,...,...,...,...
3588,1131780,"Whiteboard Animation, Beginner To Expert - In ...",True,20,1343,25,16,All Levels,1 hour,2017-03-14T20:52:30Z,Graphic Design
3594,908664,Word Swag : Create Stunning Images with the Wo...,True,100,2416,19,14,All Levels,1 hour,2016-08-09T17:56:53Z,Graphic Design
3639,1122306,Wordpress: Comment utiliser le thème FABLE,True,20,1,0,10,Beginner Level,39 mins,2017-03-07T16:53:27Z,Graphic Design
3671,144222,"YOU can Draw, Shade and Paint a Mixed Media Gi...",True,30,1249,44,19,Beginner Level,3 hours,2014-01-28T02:30:26Z,Graphic Design
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

In [30]:
udemy_courses[(udemy_courses.subject == 'Graphic Design') & (udemy_courses.price < '100')]

Empty DataFrame
Columns: [course_id, course_title, is_paid, price, num_subscribers, num_reviews, num_lectures, level, content_duration, published_timestamp, subject]
Index: []

In [31]:
# price is = $100
udemy_courses[(udemy_courses.subject == 'Graphic Design') & (udemy_courses.price == '100')]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
47,1269190,7 Secrets To Designing In Black and White,True,100,1000,1,12,All Levels,1.5 hours,2017-06-27T19:55:18Z,Graphic Design
169,983444,Adobe Illustrator Vectors For Hand Letterers,True,100,23,2,9,Beginner Level,37 mins,2016-10-21T18:50:38Z,Graphic Design
184,638040,Adobe Photoshop Essentials: Master Adobe Photo...,True,100,1373,5,63,Beginner Level,2.5 hours,2015-11-18T17:47:26Z,Graphic Design
520,978462,Blender Modelling Series - Volume Two,True,100,1526,3,24,Beginner Level,2 hours,2016-10-12T20:22:14Z,Graphic Design
699,757900,Canva : Book Cover Design,True,100,3377,20,15,Beginner Level,2 hours,2016-02-26T01:08:20Z,Graphic Design
1029,1160004,Design a logo for FREE in Inkscape,True,100,1148,26,42,All Levels,2 hours,2017-05-01T18:32:43Z,Graphic Design
1071,1161864,Diseño impreso - Preimpresión para offset en I...,True,100,33,9,29,All Levels,1.5 hours,2017-05-31T18:37:31Z,Graphic Design
1444,490392,Getting Started with Illustrator CC,True,100,92,10,57,Beginner Level,5.5 hours,2015-05-01T21:29:51Z,Graphic Design
1568,727510,How To Become An Etsy Wholesale Seller,True,100,1013,0,25,Beginner Level,2.5 hours,2016-03-29T22:34:30Z,Graphic Design
1616,996868,How to Design a Logo in Adobe Illustrator,True,100,972,44,24,All Levels,1 hour,2016-11-14T15:26:17Z,Graphic Design
1697,654038,How To Sell Your Art Online With ETSY,True,100,1338,38,35,Beginner Level,3 hours,2015-11-11T01:26:13Z,Graphic Design
1773,1012262,Icon & Logo Symbol Design in Adobe Illustrator,True,100,1043,27,30,All Levels,2 hours,2016-11-23T22:57:18Z,Graphic Design
1786,1246168,"Illustrator para criação de peças gráficas, De...",True,100,33,3,41,Beginner Level,1.5 hours,2017-06-13T04:15:20Z,Graphic Design
1797,1266468,Indesign - Para quem quer trabalhar com Design...,True,100,27,7,12,Intermediate Level,2.5 hours,2017-06-27T02:48:29Z,Graphic Design
2137,927186,Learn Blender 3D - The introduction course,True,100,739,12,15,Beginner Level,1.5 hours,2016-08-19T00:52:30Z,Graphic Design
2481,1027080,Logo Portfolio in 1 Hour in Wordpress,True,100,734,9,36,All Levels,1 hour,2016-12-06T22:13:44Z,Graphic Design
2491,771044,"Make Money With Photoshop: Logos, Business Car...",True,100,32,4,21,All Levels,5 hours,2016-08-14T22:05:04Z,Graphic Design
2576,482924,Mastering Retouching and Restoration (15 proje...,True,100,4927,15,22,All Levels,2.5 hours,2015-04-26T12:27:22Z,Graphic Design
2704,950894,photoshop - CURSO DE PHOTOSHOP DO BÁSICO AO AV...,True,100,1110,183,77,All Levels,10 hours,2017-02-06T17:22:18Z,Graphic Design
2706,1243016,Photoshop - Tratamento de pele profissional,True,100,50,5,16,Intermediate Level,1.5 hours,2017-06-06T14:22:28Z,Graphic Design
2713,1147664,Photoshop CC Eğitim Seti (YENİ),True,100,27,5,202,All Levels,16 hours,2017-03-30T22:26:26Z,Graphic Design
3479,575040,Typography From A to Z,True,100,317,15,76,All Levels,6 hours,2015-08-07T22:16:26Z,Graphic Design
3594,908664,Word Swag : Create Stunning Images with the Wo...,True,100,2416,19,14,All Levels,1 hour,2016-08-09T17:56:53Z,Graphic Design

    Use str. contains functions and course_title column
Q8: Find out all the courses which are related to Python.

In [32]:
udemy_courses.head(2)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments

In [33]:
udemy_courses[udemy_courses.course_title.str.contains('Python')]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
216,599504,Advanced Scalable Python Web Development Using...,True,120,1299,56,71,Intermediate Level,14 hours,2016-08-11T22:09:24Z,Web Development
777,47963,"Coding for Entrepreneurs: Learn Python, Django...",True,195,23412,799,251,All Levels,45 hours,2013-04-08T00:46:14Z,Web Development
814,631128,Complete Python Web Course: Build 8 Python Web...,True,110,7489,941,173,All Levels,16 hours,2015-11-08T20:57:35Z,Web Development
842,186096,"Core: A Web App Reference Guide for Django, Py...",True,195,2497,98,154,All Levels,26 hours,2014-05-29T00:58:43Z,Web Development
1400,394832,Fun and creative web engineering with Python a...,False,Free,10917,319,25,All Levels,2 hours,2015-06-09T19:51:50Z,Web Development
1932,1038538,Introduction to QGIS Python Programming,True,85,197,26,28,Beginner Level,3.5 hours,2016-12-22T00:11:22Z,Web Development
1969,902888,Investment Portfolio Analysis with Python,True,50,209,13,37,All Levels,7 hours,2016-07-13T21:40:32Z,Business Finance
2294,391546,Learn Python and Django: Payment Processing,True,70,17714,198,23,All Levels,3.5 hours,2015-02-09T15:37:56Z,Web Development
2295,1063722,Learn Python Django - A Hands-On Course,True,50,1339,21,18,Beginner Level,2 hours,2017-01-18T21:53:34Z,Web Development
2341,546848,Learn to code in Python and learn Adobe Photos...,True,50,1132,1,29,All Levels,2 hours,2015-07-08T00:15:12Z,Graphic Design
2906,368340,Professional Python Web Development Using Flask,True,120,3420,489,102,Beginner Level,14.5 hours,2015-03-04T00:10:36Z,Web Development
2908,1035940,Professional RESTful API Design using Python F...,True,120,578,25,36,Intermediate Level,4.5 hours,2017-01-11T21:15:25Z,Web Development
2929,270808,Projects in Django and Python,True,60,1764,53,28,All Levels,6.5 hours,2014-10-21T07:58:07Z,Web Development
2952,1170894,Python Algo Stock Trading: Automate Your Trading!,True,95,1165,21,41,Beginner Level,2.5 hours,2017-05-28T23:41:03Z,Business Finance
2953,1070886,Python Algo Trading: FX Trading with Oanda,True,200,453,42,33,Intermediate Level,3 hours,2017-03-14T00:39:45Z,Business Finance
2954,1196544,Python Algo Trading: Sentiment Trading with News,True,200,294,19,42,All Levels,7 hours,2017-04-28T16:41:44Z,Business Finance
2955,822444,Python and Django Full Stack Web Developer Boo...,True,200,11832,1883,191,All Levels,31.5 hours,2017-02-24T18:40:55Z,Web Development
2956,477702,Python for Beginners: Python Programming Langu...,True,150,6153,125,84,Beginner Level,5 hours,2015-06-14T18:18:57Z,Web Development
2957,1035472,Python for Finance: Investment Fundamentals & ...,True,195,3811,278,103,All Levels,6.5 hours,2017-03-30T22:17:09Z,Business Finance
2958,529828,Python for Trading & Investing,True,95,638,25,36,All Levels,5 hours,2015-06-17T22:23:31Z,Business Finance
2959,70640,Python Programming: Create an Digital Marketpl...,True,195,4198,145,161,All Levels,26 hours,2013-10-20T19:53:28Z,Web Development
2960,523312,Python Web Programming,True,100,1020,46,60,Beginner Level,6 hours,2015-07-01T21:46:36Z,Web Development
2962,1088656,Quantitative Trading Analysis with Python,True,50,256,17,49,All Levels,5.5 hours,2017-01-27T17:11:28Z,Business Finance
3013,970600,REST APIs with Flask and Python,True,110,5151,737,115,Intermediate Level,12.5 hours,2016-11-06T19:00:38Z,Web Development
3154,815482,Stock Technical Analysis with Python,True,50,409,35,46,All Levels,8 hours,2016-04-12T00:40:03Z,Business Finance
3272,938560,The Complete Ethical Hacking Course 2.0: Pytho...,True,195,7827,268,66,All Levels,11 hours,2016-09-26T15:08:29Z,Web Development
3460,76052,Try Django 1.9 | Build a Blog and Learn Python...,True,50,7407,172,147,All Levels,20 hours,2014-03-04T07:12:21Z,Web Development
3573,16646,Web Programming with Python,True,50,35267,217,53,All Levels,4 hours,2012-04-25T00:01:43Z,Web Development
3574,574082,"Web Scraping with Python, Ruby & import. io",True,75,973,50,46,All Levels,4.5 hours,2015-08-09T22:16:41Z,Web Development

In [34]:
udemy_courses[udemy_courses.course_title.str.contains('Python')].shape

(29, 11)

In [35]:
len(udemy_courses[udemy_courses.course_title.str.contains('Python')])

29

Q9: Courses published in 2017.

In [36]:
udemy_courses.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments

In [37]:
# To check the datatype of each column
udemy_courses.dtypes

course_id               int64
course_title           object
is_paid                  bool
price                  object
num_subscribers         int64
num_reviews             int64
num_lectures            int64
level                  object
content_duration       object
published_timestamp    object
subject                object
dtype: object

In [38]:
# Convert object to date time function(published_timestamp column)
udemy_courses['published_timestamp'] = pd.to_datetime(udemy_courses.published_timestamp)

In [39]:
udemy_courses.dtypes

course_id                            int64
course_title                        object
is_paid                               bool
price                               object
num_subscribers                      int64
num_reviews                          int64
num_lectures                         int64
level                               object
content_duration                    object
published_timestamp    datetime64[ns, UTC]
subject                             object
dtype: object

In [40]:
# To check the date-time function
udemy_courses.head(2)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18 05:07:05+00:00,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12 19:06:34+00:00,Musical Instruments

In [41]:
# To add new column which shows only year(try month or date as well)
udemy_courses['Year'] = udemy_courses['published_timestamp'].dt.year

In [42]:
udemy_courses.head()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18 05:07:05+00:00,Musical Instruments,2014
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12 19:06:34+00:00,Musical Instruments,2017
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26 18:34:57+00:00,Musical Instruments,2017
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21 23:48:18+00:00,Musical Instruments,2017
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21 23:44:49+00:00,Musical Instruments,2017

In [43]:
# To check 2017 published courses or different years
udemy_courses[udemy_courses.Year == 2017]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12 19:06:34+00:00,Musical Instruments,2017
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26 18:34:57+00:00,Musical Instruments,2017
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21 23:48:18+00:00,Musical Instruments,2017
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21 23:44:49+00:00,Musical Instruments,2017
5,1122832,#6 Piano Hand Coordination: Play Open 10 Balla...,True,65,2015,3,21,Intermediate Level,44 mins,2017-03-08 17:53:36+00:00,Musical Instruments,2017
...,...,...,...,...,...,...,...,...,...,...,...,...
3662,1115132,XML XQuery - Crash Course for Beginners,True,45,426,4,10,All Levels,1 hour,2017-02-19 22:52:36+00:00,Web Development,2017
3663,1115126,XML XSLT - Crash Course for Beginners,True,45,426,4,9,All Levels,1 hour,2017-02-19 18:11:07+00:00,Web Development,2017
3672,1031698,You Can Play Jazz Saxophone,True,20,37,7,6,Beginner Level,1.5 hours,2017-03-15 16:20:15+00:00,Musical Instruments,2017
3674,1257976,Your First 10 Guitar Lessons - Learn how to pl...,False,Free,924,4,18,Beginner Level,1 hour,2017-06-29 00:29:36+00:00,Musical Instruments,2017
3680,1225194,Zoho Books Gestion Financière d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26 16:45:55+00:00,Business Finance,2017

In [44]:
udemy_courses[udemy_courses.Year == 2017].shape

(719, 12)

In [46]:
# To check the length
len(udemy_courses[udemy_courses.Year == 2017])

719

    Use groupby function(level and num_subscribers columns)
Q10: What are the maximum number of subscribers for each level of course?

In [47]:
udemy_courses.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18 05:07:05+00:00,Musical Instruments,2014

In [48]:
udemy_courses.level.unique()

array(['All Levels', 'Intermediate Level', 'Beginner Level',
       'Expert Level'], dtype=object)

In [49]:
udemy_courses.groupby('level')['num_subscribers'].max()

level
All Levels            268923
Beginner Level        161029
Expert Level            5172
Intermediate Level     29167
Name: num_subscribers, dtype: int64

In [50]:
udemy_courses.groupby('level')['num_subscribers'].min()

level
All Levels            0
Beginner Level        0
Expert Level          1
Intermediate Level    0
Name: num_subscribers, dtype: int64

In [51]:
udemy_courses.groupby('level').max()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,content_duration,published_timestamp,subject,Year
level,,,,,,,,,,,
All Levels,1277924,６時間でインターバンク市場を攻略！最短距離でトレード基礎力,True,Free,268923,27445,544,9.5 hours,2017-07-06 21:16:13+00:00,Web Development,2017
Beginner Level,1282064,７日でマスター ビギナー向け Adobe Illustrator どきどきセミナー,True,Free,161029,5924,779,9.5 hours,2017-07-06 21:46:30+00:00,Web Development,2017
Expert Level,1275790,[Value Investing] Where White People Keep Thei...,True,95,5172,249,157,9 hours,2017-07-04 18:08:01+00:00,Web Development,2017
Intermediate Level,1276182,株式投資で本当のテクニカル分析ができるようになる,True,Free,29167,3326,320,9.5 hours,2017-07-05 04:41:54+00:00,Web Development,2017